name: Deploy to portfolio

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy to portfolio repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PORTFOLIO_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'paulapereda'
          destination-repository-name: 'portfolio'
          target-directory: 'radiografia-infancia'
          destination-branch: main
